---
title: "Comparing results from old and new siteB data"
author: "Maddy"
initiation_date: "13/04/2023"
output:
  html_document: default
---

<style type="text/css">
div.main-container {
  max-width: 100%;
  margin-left: auto;
  margin-right: auto;
}
</style>

<style>
pre {
  overflow-x: auto;
}
pre code {
  word-wrap: normal;
  white-space: pre;
}
</style>

```{r global_options, echo = FALSE, include = FALSE}
options(width = 999)
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE,
                      cache = FALSE, tidy = FALSE, size = "small")
```

```{r setup, results='asis', echo=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# read in parameter file
source("parameter_files/17.parameters.R")

# load libraries
library(readxl)
library(tidyr)
library(dplyr)
library(ggplot2)
library(tidyverse)
library(gtools)
library(qqman)
library(ggpubr)
library(ggrepel)
library(blandr)

```


```{r compare raw data, echo=FALSE, eval=TRUE}
# read in the two datasets to compare the raw data for some metabs - can compare raw and rnt'd
# new data
load(paste0(data_output_dir, "intermediate/01_dataset_list.RData"))
## keep only siteB samples
siteB_mainfest <- read.csv(siteB_manifest)
siteB <- siteB_mainfest[,"Study.Identifier"]
for (i in 1:length(dataset_list)) {
  w <- which(dataset_list[[i]]$studyid %in% siteB)
  dataset_list[[i]] <- dataset_list[[i]][w,]
}
new_raw <- dataset_list$raw
new_rnt <- dataset_list$rnt_raw

# restrict to features included in latest QC (extra 77 removed for low N)
feature_data <- read.csv(feature_metadata_file,h=T,sep="\t")
compids_to_keep <- (which(names(new_raw) %in% feature_data$feature_id))
new_raw <- new_raw[,c(1:54,compids_to_keep)]
dim(new_raw)

compids_to_keep <- (which(names(new_rnt) %in% feature_data$feature_id))
new_rnt <- new_rnt[,c(1:54,compids_to_keep)]
dim(new_rnt)

# old data
old <- readRDS(file=paste0(old_siteB_dir,"01_dataset_list.rds"))
old_raw <- old$raw$metabolon
old_rnt <- old$rnt_imputed$metabolon

# sample IDs might not match (different tubes) so create a studyID/timepoint var to match on (need to make 36 months end instead)
old_raw$Visit.Identifier <- gsub("36 months", "end", old_raw$Visit.Identifier)
old_rnt$Visit.Identifier <- gsub("36 months", "end", old_rnt$Visit.Identifier)
old_raw$id_timepoint <- paste0(old_raw$Study.Identifier, "_", old_raw$Visit.Identifier)
old_rnt$id_timepoint <- paste0(old_rnt$Study.Identifier, "_", old_rnt$Visit.Identifier)


```


### Distribution of R values from cor(old, new)
```{r distribution of correlations in raw, echo=FALSE}
dat <- merge(new_raw, old_raw, by = "id_timepoint", all.x = T)
columns_with_metabolite_data <- which(grepl( "compid" , names(dat))==TRUE)
dat <- dat[,c(1, columns_with_metabolite_data)]

# Create an empty dataframe to store results
r_df <- data.frame(metabolite = character(),
                   n = numeric(),
                           r = numeric(),
                   p = numeric(),
                           stringsAsFactors = FALSE)


# Define a vector of metabolite names
metabolite_names <- colnames(new_raw[,which(grepl( "compid" , names(new_raw))==TRUE)])

# empty list for ba plots
plot_list_ba = list()
# collect metab names that dont run in comparison (ebcause only exit in one dataset)
missing_metabs <- c()
count_missing <- 0
count_present <- 0

# Loop over metabolite names
for (metabolite in metabolite_names) {
  
  # Select data for the metabolite
  dat_metabolite <- na.omit(dat[, grep(paste0(metabolite, "\\.[xy]$"), colnames(dat))])
  
  # Check if there are two columns with the same name
  if (ncol(dat_metabolite) == 2 & nrow(dat_metabolite)>=3) {
    count_present = count_present + 1
    
    # Calculate correlation coefficient
    r <- cor.test(dat_metabolite[, 1], dat_metabolite[, 2], method = "spearman")
    
    # Add results to dataframe
    r_df <- rbind(r_df, data.frame(metabolite = metabolite, n = nrow(dat_metabolite), r = r$estimate, p = r$p.value))
    
    # bland-altman
    blandr_out <- blandr.statistics(scale(dat_metabolite[, 1]), scale(dat_metabolite[, 2]), sig.level = 0.95, LoA.mode = 1)
    blandr_out
    plot_list_ba[[metabolite]] <- blandr.plot.ggplot(blandr_out, method1name = "1", method2name = "2", 
                                                plotTitle= paste0(metabolite))

  }
  else {
    count_missing = count_missing + 1
    missing_metabs[count_missing] <- metabolite
  }
}

# View distribution of r

ggplot(r_df, aes(x=r)) + geom_histogram(bins = 30, fill="lightgray", colour="black") +
  xlab("Spearman's correlation coefficient (r)") +
  ylab("Number of metabolites") +
  ggtitle("") +
  geom_vline(xintercept = median(r_df$r), colour = "red",size=1) +
  theme_classic() + # Start with a classic theme that removes gridlines
  theme(
    panel.background = element_blank(), # Remove panel background
    panel.grid.major = element_blank(), # Remove major gridlines
    panel.grid.minor = element_blank(), # Remove minor gridlines
    axis.line = element_line(colour = "black"), # Add axis lines
    axis.ticks = element_line(colour = "black"), # Add axis ticks
    axis.text = element_text(color = "black"), # Black axis labels
    axis.title = element_text(color = "black"), # Black axis titles
    plot.background = element_blank(), # Remove plot background
    legend.position = "none" # Remove legend if not needed
  )
ggsave(paste0(fig_dir, "Fig4_raw_spearmans_R_histogram.jpeg"), dpi=600)

# save out r_df for the raw data - will use this to see if we trust the results for each metab
write.csv(r_df, file = paste0(table_dir, "spearmans_correlation_results.csv"), row.names = F)

# merge in the feature data
r_df_features <- merge(r_df, feature_data, by.x = "metabolite", by.y = "feature_id")
# order by R
r_df_features <- r_df_features[order(r_df_features$r),]
# count the super pathways in those with R <5
table(r_df_features[which(r_df_features$r<0.5),"SUPER_PATHWAY"])
# calculate missingness for each metab
r_df_features$missing <- ((250-r_df_features$n.x)/250)*100
write.csv(r_df_features, file = paste0(table_dir, "TableS1_pilot_compare.csv"), row.names = F)

print("Number of metabolites compared:")
length(plot_list_ba)

print("Number of metabolites not compared:")
length(missing_metabs)

print("total number of metabolites:")
length(metabolite_names)

filename = paste0(fig_dir,"FigS2_assay_comparison.pdf")
outputfig <- ggpubr::ggarrange(plotlist=plot_list_ba,
                               ncol=2, nrow=3,
                               common.legend = T,
                               legend="top",
                               heights = 2,
                               widths = 2)
ggpubr::ggexport(outputfig, filename=filename)
```



